-- MySQL Script generated by MySQL Workbench
-- Thu Jan 18 21:39:06 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema house_finder_project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema house_finder_project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `house_finder_project` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `house_finder_project` ;

-- -----------------------------------------------------
-- Table `house_finder_project`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `house_finder_project`.`role` ;

CREATE TABLE IF NOT EXISTS `house_finder_project`.`role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `house_finder_project`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `house_finder_project`.`user` ;

CREATE TABLE IF NOT EXISTS `house_finder_project`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(250) NULL DEFAULT NULL,
  `date_of_birth` DATE NULL DEFAULT NULL,
  `address` VARCHAR(250) NULL DEFAULT NULL,
  `phone_number` INT NULL DEFAULT NULL,
  `email` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `house_finder_project`.`account`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `house_finder_project`.`account` ;

CREATE TABLE IF NOT EXISTS `house_finder_project`.`account` (
  `user_id` INT NOT NULL,
  `user_name` VARCHAR(45) NULL DEFAULT NULL,
  `pass_word` VARCHAR(45) NULL DEFAULT NULL,
  `role_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `role_id_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `house_finder_project`.`role` (`role_id`),
  CONSTRAINT `user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `house_finder_project`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `house_finder_project`.`request_status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `house_finder_project`.`request_status` ;

CREATE TABLE IF NOT EXISTS `house_finder_project`.`request_status` (
  `status_id` INT NOT NULL AUTO_INCREMENT,
  `status_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`status_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `house_finder_project`.`type_of_house`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `house_finder_project`.`type_of_house` ;

CREATE TABLE IF NOT EXISTS `house_finder_project`.`type_of_house` (
  `type_of_house_id` INT NOT NULL AUTO_INCREMENT,
  `type_of_house_name` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`type_of_house_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `house_finder_project`.`house`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `house_finder_project`.`house` ;

CREATE TABLE IF NOT EXISTS `house_finder_project`.`house` (
  `house_id` INT NOT NULL AUTO_INCREMENT,
  `house_owner_id` INT NULL DEFAULT NULL,
  `type_of_house_id` INT NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `area` INT NULL DEFAULT NULL,
  `number_of_room` INT NULL DEFAULT NULL,
  PRIMARY KEY (`house_id`),
  INDEX `type_of_house_id_idx` (`type_of_house_id` ASC) VISIBLE,
  INDEX `house_owner_id_idx` (`house_owner_id` ASC) VISIBLE,
  CONSTRAINT `owner_id`
    FOREIGN KEY (`house_owner_id`)
    REFERENCES `house_finder_project`.`user` (`user_id`),
  CONSTRAINT `type_of_house_id`
    FOREIGN KEY (`type_of_house_id`)
    REFERENCES `house_finder_project`.`type_of_house` (`type_of_house_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `house_finder_project`.`post`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `house_finder_project`.`post` ;

CREATE TABLE IF NOT EXISTS `house_finder_project`.`post` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `house_id` INT NOT NULL,
  `purpose` VARCHAR(45) NULL DEFAULT NULL,
  `price` DECIMAL(10,0) NULL DEFAULT NULL,
  `poster_id` INT NULL DEFAULT NULL,
  `house_status` TINYINT(1) NULL DEFAULT NULL,
  `admin_id` INT NULL DEFAULT NULL,
  `post_status` INT NULL DEFAULT NULL,
  PRIMARY KEY (`post_id`, `house_id`),
  INDEX `house_id_idx` (`house_id` ASC) VISIBLE,
  INDEX `user_id_idx` (`poster_id` ASC) VISIBLE,
  INDEX `admin_id_idx` (`admin_id` ASC) VISIBLE,
  INDEX `post_status_idx` (`post_status` ASC) VISIBLE,
  CONSTRAINT `censor_id`
    FOREIGN KEY (`admin_id`)
    REFERENCES `house_finder_project`.`user` (`user_id`),
  CONSTRAINT `post_status`
    FOREIGN KEY (`post_status`)
    REFERENCES `house_finder_project`.`request_status` (`status_id`),
  CONSTRAINT `poster_id`
    FOREIGN KEY (`poster_id`)
    REFERENCES `house_finder_project`.`user` (`user_id`),
  CONSTRAINT `product_id`
    FOREIGN KEY (`house_id`)
    REFERENCES `house_finder_project`.`house` (`house_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `house_finder_project`.`feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `house_finder_project`.`feedback` ;

CREATE TABLE IF NOT EXISTS `house_finder_project`.`feedback` (
  `post_id` INT NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `number_of_star` INT NULL DEFAULT NULL,
  `comment` VARCHAR(250) CHARACTER SET 'utf8mb3' NULL DEFAULT NULL,
  PRIMARY KEY (`post_id`),
  INDEX `user_id_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `assessor_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `house_finder_project`.`user` (`user_id`),
  CONSTRAINT `post_id`
    FOREIGN KEY (`post_id`)
    REFERENCES `house_finder_project`.`post` (`post_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `house_finder_project`.`request`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `house_finder_project`.`request` ;

CREATE TABLE IF NOT EXISTS `house_finder_project`.`request` (
  `house_id` INT NOT NULL,
  `seller_id` INT NOT NULL,
  `customer_id` INT NOT NULL,
  `purpose` VARCHAR(45) NULL DEFAULT NULL,
  `request_status` INT NULL DEFAULT NULL,
  `date_time` DATETIME NOT NULL,
  PRIMARY KEY (`house_id`, `seller_id`, `customer_id`, `date_time`),
  INDEX `house_owner_id_idx` (`seller_id` ASC) VISIBLE,
  INDEX `customer_idx` (`customer_id` ASC) VISIBLE,
  INDEX `request_status_idx` (`request_status` ASC) VISIBLE,
  CONSTRAINT `seller_id`
    FOREIGN KEY (`seller_id`)
    REFERENCES `house_finder_project`.`user` (`user_id`),
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `house_finder_project`.`user` (`user_id`),
  CONSTRAINT `property_id`
    FOREIGN KEY (`house_id`)
    REFERENCES `house_finder_project`.`house` (`house_id`),
  CONSTRAINT `request_status`
    FOREIGN KEY (`request_status`)
    REFERENCES `house_finder_project`.`request_status` (`status_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
