-- MySQL Script generated by MySQL Workbench
-- Tue Jan 16 08:11:14 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema house_finder
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema house_finder
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `house_finder` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `house_finder` ;

-- -----------------------------------------------------
-- Table `house_finder`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `house_finder`.`role` (
  `role_id` INT NOT NULL AUTO_INCREMENT,
  `role_name` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`role_id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `house_finder`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `house_finder`.`user` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `full_name` VARCHAR(250) NULL DEFAULT NULL,
  `user_name` VARCHAR(250) NULL DEFAULT NULL,
  `password` VARCHAR(250) NULL DEFAULT NULL,
  `role_id` INT NULL DEFAULT NULL,
  `location` VARCHAR(250) NULL DEFAULT NULL,
  `phone` VARCHAR(11) NULL DEFAULT NULL,
  `email` VARCHAR(250) NULL DEFAULT NULL,
  PRIMARY KEY (`user_id`),
  INDEX `roleID` (`role_id` ASC) VISIBLE,
  CONSTRAINT `user_ibfk_1`
    FOREIGN KEY (`role_id`)
    REFERENCES `house_finder`.`role` (`role_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `house_finder`.`type_of_house`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `house_finder`.`type_of_house` (
  `type_of_house_id` INT NOT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`type_of_house_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `house_finder`.`house`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `house_finder`.`house` (
  `house_id` INT NOT NULL AUTO_INCREMENT,
  `location` VARCHAR(255) NULL DEFAULT NULL,
  `type_of_house_id` INT NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `house_owner_id` INT NOT NULL,
  `price_per_unit` DECIMAL(10,2) NULL DEFAULT NULL,
  `picture` VARCHAR(255) NULL DEFAULT NULL,
  `status` TINYINT(1) NULL DEFAULT NULL,
  PRIMARY KEY (`house_id`, `house_owner_id`),
  INDEX `TypeOfHouseID` (`type_of_house_id` ASC) VISIBLE,
  INDEX `HouseOwnerID` (`house_owner_id` ASC) VISIBLE,
  CONSTRAINT `house_ibfk_1`
    FOREIGN KEY (`type_of_house_id`)
    REFERENCES `house_finder`.`type_of_house` (`type_of_house_id`),
  CONSTRAINT `house_ibfk_2`
    FOREIGN KEY (`house_owner_id`)
    REFERENCES `house_finder`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `house_finder`.`renting_house`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `house_finder`.`renting_house` (
  `house_id` INT NULL DEFAULT NULL,
  `renting_house_id` INT NOT NULL AUTO_INCREMENT,
  `renter_id` INT NULL DEFAULT NULL,
  `time_from` DATETIME NULL DEFAULT NULL,
  `time_to` DATETIME NULL DEFAULT NULL,
  `fee` DECIMAL(10,2) NULL DEFAULT NULL,
  `price_total` DECIMAL(10,2) NULL DEFAULT NULL,
  `renting_house_col` VARCHAR(45) NULL,
  PRIMARY KEY (`renting_house_id`),
  INDEX `HouseID` (`house_id` ASC) VISIBLE,
  INDEX `renterID` (`renter_id` ASC) VISIBLE,
  CONSTRAINT `rentinghouse_ibfk_1`
    FOREIGN KEY (`house_id`)
    REFERENCES `house_finder`.`house` (`house_id`),
  CONSTRAINT `rentinghouse_ibfk_2`
    FOREIGN KEY (`renter_id`)
    REFERENCES `house_finder`.`user` (`user_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `house_finder`.`feedback`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `house_finder`.`feedback` (
  `feedback_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NULL DEFAULT NULL,
  `renting_house_id` INT NULL DEFAULT NULL,
  `grade` INT NULL DEFAULT NULL,
  `discription` VARCHAR(255) NULL DEFAULT NULL,
  `time` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`feedback_id`),
  INDEX `userID` (`user_id` ASC) VISIBLE,
  INDEX `rhID` (`renting_house_id` ASC) VISIBLE,
  CONSTRAINT `feedback_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `house_finder`.`user` (`user_id`),
  CONSTRAINT `feedback_ibfk_2`
    FOREIGN KEY (`renting_house_id`)
    REFERENCES `house_finder`.`renting_house` (`renting_house_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `house_finder`.`oder_booking`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `house_finder`.`oder_booking` (
  `user_id` INT NULL DEFAULT NULL,
  `house_id` INT NULL DEFAULT NULL,
  `time` DATETIME NULL DEFAULT NULL,
  INDEX `userID` (`user_id` ASC) VISIBLE,
  INDEX `houseID` (`house_id` ASC) VISIBLE,
  CONSTRAINT `oderbooking_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `house_finder`.`user` (`user_id`),
  CONSTRAINT `oderbooking_ibfk_2`
    FOREIGN KEY (`house_id`)
    REFERENCES `house_finder`.`house` (`house_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `house_finder`.`record`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `house_finder`.`record` (
  `renter_id` INT NULL DEFAULT NULL,
  `renter_house_id` INT NULL DEFAULT NULL,
  `time` DATETIME NULL DEFAULT NULL,
  INDEX `renterID` (`renter_id` ASC) VISIBLE,
  INDEX `rhID` (`renter_house_id` ASC) VISIBLE,
  CONSTRAINT `record_ibfk_1`
    FOREIGN KEY (`renter_id`)
    REFERENCES `house_finder`.`user` (`user_id`),
  CONSTRAINT `record_ibfk_2`
    FOREIGN KEY (`renter_house_id`)
    REFERENCES `house_finder`.`renting_house` (`renting_house_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `house_finder`.`sell_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `house_finder`.`sell_post` (
  `sell_post_id` INT NOT NULL AUTO_INCREMENT,
  `house_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  `time` DATETIME NULL DEFAULT NULL,
  `type_of_house_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`sell_post_id`),
  INDEX `houseID` (`house_id` ASC) VISIBLE,
  INDEX `userID` (`user_id` ASC) VISIBLE,
  INDEX `TypeOfHouseID` (`type_of_house_id` ASC) VISIBLE,
  CONSTRAINT `sellpost_ibfk_1`
    FOREIGN KEY (`house_id`)
    REFERENCES `house_finder`.`house` (`house_id`),
  CONSTRAINT `sellpost_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `house_finder`.`user` (`user_id`),
  CONSTRAINT `sellpost_ibfk_3`
    FOREIGN KEY (`type_of_house_id`)
    REFERENCES `house_finder`.`type_of_house` (`type_of_house_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `house_finder`.`request_sell_post`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `house_finder`.`request_sell_post` (
  `request_sell_post_id` INT NOT NULL,
  `sell_post_id` INT NOT NULL,
  PRIMARY KEY (`sell_post_id`),
  CONSTRAINT `requestsellpost_ibfk_1`
    FOREIGN KEY (`sell_post_id`)
    REFERENCES `house_finder`.`sell_post` (`sell_post_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
